### ISSUE TITLE
Can't use in another project?

### ISSUE THREAD

**Issue by rjzak** [CybercentreCanada/cart-rs#1]
This may be me being dumb, but I can't seem to use this crate in my project. I've added `cart_container` to my project: `cart_container = { version = "0.1.7" }`.

I can add `use cart::digesters::default_digesters;` to my imports, and I can Ctrl-Click the function name and my IDE can bring up the file, but the compiler says:

```
error[E0433]: failed to resolve: use of undeclared crate or module `cart`
  --> crates/server/src/http/mod.rs:19:5
   |
19 | use cart::digesters::default_digesters;
   |     ^^^^ use of undeclared crate or module `cart`

error[E0433]: failed to resolve: use of undeclared crate or module `cart`
   --> crates/server/src/http/mod.rs:197:5
    |
197 |     cart::pack_stream(
    |     ^^^^ use of undeclared crate or module `cart`

For more information about this error, try `rustc --explain E0433`.
```

I also tried `cart_container` since that's the name of the crate on crates.io, but that also fails:

```
19 | use cart_container::digesters::default_digesters;
   |     ^^^^^^^^^^^^^^ use of undeclared crate or module `cart_container`

error[E0433]: failed to resolve: use of undeclared crate or module `cart_container`
   --> crates/server/src/http/mod.rs:197:5
    |
197 |     cart_container::pack_stream(
    |     ^^^^^^^^^^^^^^ use of undeclared crate or module `cart_container`

For more information about this error, try `rustc --explain E0433`.
```

Is there something unstandard about how this project is laid out? It does seem odd that `lib.rs` is all about the C interface, and that there is a distinction between `use crate::cart:...` and `use cart:...` in the imports:

https://github.com/CybercentreCanada/cart-rs/blob/79fb39c970f607b3fc823a6c0f897e8dcf61e9eb/src/lib.rs#L41-L46

Lastly, it seems I might not be the only person with this issue, since this awesome project is not a dependent of any other projects at the time of writing https://crates.io/crates/cart_container/reverse_dependencies.

**Comment by rjzak** [comment]
Code: https://github.com/malwaredb/malwaredb-rs/pull/249, error from CI: https://github.com/malwaredb/malwaredb-rs/actions/runs/7565018856/job/20600072186?pr=249

**Comment by rjzak** [comment]
What I'm seeing:
![image](https://github.com/CybercentreCanada/cart-rs/assets/1133882/9ac5e1f5-d50a-4fb0-87a4-22ebf96eeec7)

The Errors at the top of the pop-up show the errors from the compiler, yet the IDE pulls up the docs.rs page.

**Comment by binaryninja** [comment]
Just want to add I'm getting the same error  byt following the same steps.  I'm brand new to rust so it may be a simple thing.

I also did a cargo add cart_container insinde my project dir but that didn't help...

**Comment by cccs-douglass** [comment]
This was the first time I tried to build a rust package also as a C package and I need to adjust some things. Thanks for letting me know I goofed.

**Comment by rjzak** [comment]
No worries, I haven't done a Rust/C project before either so I wasn't able to resolve it when I tried.

**Comment by cccs-douglass** [comment]
It should work now, though the interface isn't very ergonomic that is an issue for another day. Also added an example to the lib.rs docstring.

**Comment by rjzak** [comment]
Works now! Version 0.1.8. Thank you.
